language: scala
scala:
  - 2.12.10
  - 2.13.1
jdk:
  - oraclejdk11

matrix:
  include:
    - jdk: oraclejdk8
      dist: trusty
      scala: 2.12.10
    - jdk: oraclejdk8
      dist: trusty
      scala: 2.13.1

script:
  - sbt clean coverage test
